name: Build and deploy Node.js app to Azure Web App - basic-node

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install, build
        run: |
          cd server
          npm install
          cd ..
          cd client
          npm install --force
          npm run build --if-present
