# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - NodeChat123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build
        run: |
          cd server
          npm install
          cd ..
          npm install --force
          npm run build --if-present
      
      - name: Upload node-js for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-js
          path: server
          
      - name: Upload react for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: react-js
          path: client/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-js
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: react-js

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'NodeChat123'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5FFCF5BECE904BA68556B290D324649C }}
          package: .
